// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataService.proto

package alluxio.client.file.cache.remote.grpc.service;

public interface DataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 file_id = 1;</code>
   */
  long getFileId();

  /**
   * <code>int64 begin = 2;</code>
   */
  long getBegin();

  /**
   * <code>int64 end = 3;</code>
   */
  long getEnd();
}
