// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataService.proto

package alluxio.client.file.cache.remote.grpc.service;

public final class DataServiceManager {
  private DataServiceManager() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DataRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021dataService.proto\022\005proto\"\024\n\004Data\022\014\n\004da" +
      "ta\030\001 \001(\014\":\n\013DataRequest\022\017\n\007file_id\030\001 \001(\003" +
      "\022\r\n\005begin\030\002 \001(\003\022\013\n\003end\030\003 \001(\0032A\n\013DataServ" +
      "ice\0222\n\013requestData\022\022.proto.DataRequest\032\013" +
      ".proto.Data\"\0000\001BJ\n,alluxio.client.file.c" +
      "ache.remote.net.serviceB\022DataServiceMana" +
      "gerP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Data_descriptor,
        new String[] { "Data", });
    internal_static_proto_DataRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_DataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DataRequest_descriptor,
        new String[] { "FileId", "Begin", "End", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
