// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataService.proto

package alluxio.client.file.cache.remote.grpc.service;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();
}
