// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metedataService.proto

package alluxio.client.file.cache.remote.grpc.service;

/**
 * Protobuf type {@code proto.fileInfo}
 */
public  final class fileInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.fileInfo)
    fileInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use fileInfo.newBuilder() to construct.
  private fileInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private fileInfo() {
    fileId_ = 0L;
    fileLength_ = 0L;
    begin_ = 0L;
    end_ = 0L;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private fileInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 24: {

            fileId_ = input.readInt64();
            break;
          }
          case 32: {

            fileLength_ = input.readInt64();
            break;
          }
          case 40: {

            begin_ = input.readInt64();
            break;
          }
          case 48: {

            end_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MetedataServiceManager.internal_static_proto_fileInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MetedataServiceManager.internal_static_proto_fileInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            fileInfo.class, Builder.class);
  }

  public static final int FILE_ID_FIELD_NUMBER = 3;
  private long fileId_;
  /**
   * <code>int64 file_id = 3;</code>
   */
  public long getFileId() {
    return fileId_;
  }

  public static final int FILE_LENGTH_FIELD_NUMBER = 4;
  private long fileLength_;
  /**
   * <code>int64 file_length = 4;</code>
   */
  public long getFileLength() {
    return fileLength_;
  }

  public static final int BEGIN_FIELD_NUMBER = 5;
  private long begin_;
  /**
   * <code>int64 begin = 5;</code>
   */
  public long getBegin() {
    return begin_;
  }

  public static final int END_FIELD_NUMBER = 6;
  private long end_;
  /**
   * <code>int64 end = 6;</code>
   */
  public long getEnd() {
    return end_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fileId_ != 0L) {
      output.writeInt64(3, fileId_);
    }
    if (fileLength_ != 0L) {
      output.writeInt64(4, fileLength_);
    }
    if (begin_ != 0L) {
      output.writeInt64(5, begin_);
    }
    if (end_ != 0L) {
      output.writeInt64(6, end_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fileId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, fileId_);
    }
    if (fileLength_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, fileLength_);
    }
    if (begin_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, begin_);
    }
    if (end_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, end_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof fileInfo)) {
      return super.equals(obj);
    }
    fileInfo other = (fileInfo) obj;

    boolean result = true;
    result = result && (getFileId()
        == other.getFileId());
    result = result && (getFileLength()
        == other.getFileLength());
    result = result && (getBegin()
        == other.getBegin());
    result = result && (getEnd()
        == other.getEnd());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILE_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFileId());
    hash = (37 * hash) + FILE_LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFileLength());
    hash = (37 * hash) + BEGIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBegin());
    hash = (37 * hash) + END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEnd());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static fileInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fileInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fileInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fileInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fileInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static fileInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static fileInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fileInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static fileInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static fileInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static fileInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static fileInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(fileInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.fileInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.fileInfo)
      alluxio.client.file.cache.remote.grpc.service.fileInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MetedataServiceManager.internal_static_proto_fileInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MetedataServiceManager.internal_static_proto_fileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fileInfo.class, Builder.class);
    }

    // Construct using alluxio.client.file.cache.remote.net.service.fileInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      fileId_ = 0L;

      fileLength_ = 0L;

      begin_ = 0L;

      end_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MetedataServiceManager.internal_static_proto_fileInfo_descriptor;
    }

    @Override
    public fileInfo getDefaultInstanceForType() {
      return fileInfo.getDefaultInstance();
    }

    @Override
    public fileInfo build() {
      fileInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public fileInfo buildPartial() {
      fileInfo result = new fileInfo(this);
      result.fileId_ = fileId_;
      result.fileLength_ = fileLength_;
      result.begin_ = begin_;
      result.end_ = end_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof fileInfo) {
        return mergeFrom((fileInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(fileInfo other) {
      if (other == fileInfo.getDefaultInstance()) return this;
      if (other.getFileId() != 0L) {
        setFileId(other.getFileId());
      }
      if (other.getFileLength() != 0L) {
        setFileLength(other.getFileLength());
      }
      if (other.getBegin() != 0L) {
        setBegin(other.getBegin());
      }
      if (other.getEnd() != 0L) {
        setEnd(other.getEnd());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      fileInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (fileInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long fileId_ ;
    /**
     * <code>int64 file_id = 3;</code>
     */
    public long getFileId() {
      return fileId_;
    }
    /**
     * <code>int64 file_id = 3;</code>
     */
    public Builder setFileId(long value) {
      
      fileId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 file_id = 3;</code>
     */
    public Builder clearFileId() {
      
      fileId_ = 0L;
      onChanged();
      return this;
    }

    private long fileLength_ ;
    /**
     * <code>int64 file_length = 4;</code>
     */
    public long getFileLength() {
      return fileLength_;
    }
    /**
     * <code>int64 file_length = 4;</code>
     */
    public Builder setFileLength(long value) {
      
      fileLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 file_length = 4;</code>
     */
    public Builder clearFileLength() {
      
      fileLength_ = 0L;
      onChanged();
      return this;
    }

    private long begin_ ;
    /**
     * <code>int64 begin = 5;</code>
     */
    public long getBegin() {
      return begin_;
    }
    /**
     * <code>int64 begin = 5;</code>
     */
    public Builder setBegin(long value) {
      
      begin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 begin = 5;</code>
     */
    public Builder clearBegin() {
      
      begin_ = 0L;
      onChanged();
      return this;
    }

    private long end_ ;
    /**
     * <code>int64 end = 6;</code>
     */
    public long getEnd() {
      return end_;
    }
    /**
     * <code>int64 end = 6;</code>
     */
    public Builder setEnd(long value) {
      
      end_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 end = 6;</code>
     */
    public Builder clearEnd() {
      
      end_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.fileInfo)
  }

  // @@protoc_insertion_point(class_scope:proto.fileInfo)
  private static final fileInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new fileInfo();
  }

  public static fileInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<fileInfo>
      PARSER = new com.google.protobuf.AbstractParser<fileInfo>() {
    @Override
    public fileInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new fileInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<fileInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<fileInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public fileInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

