// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metedataService.proto

package alluxio.client.file.cache.remote.grpc.service;

public interface fileInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.fileInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 file_id = 3;</code>
   */
  long getFileId();

  /**
   * <code>int64 file_length = 4;</code>
   */
  long getFileLength();

  /**
   * <code>int64 begin = 5;</code>
   */
  long getBegin();

  /**
   * <code>int64 end = 6;</code>
   */
  long getEnd();
}
