// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metedataService.proto

package alluxio.client.file.cache.remote.grpc.service;

public final class MetedataServiceManager {
  private MetedataServiceManager() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_QueryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_QueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_QueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_fileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_fileInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateInfoList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateInfoList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025metedataService.proto\022\005proto\";\n\rQueryR" +
      "esponse\022\020\n\010is_exist\030\001 \001(\010\022\n\n\002ip\030\002 \001(\t\022\014\n" +
      "\004port\030\003 \001(\005\";\n\014QueryRequest\022\017\n\007file_id\030\001" +
      " \001(\003\022\r\n\005begin\030\002 \001(\003\022\013\n\003end\030\003 \001(\003\"G\n\nUpda" +
      "teInfo\022\014\n\004host\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\035\n\004in" +
      "fo\030\003 \001(\0132\017.proto.fileInfo\"L\n\010fileInfo\022\017\n" +
      "\007file_id\030\003 \001(\003\022\023\n\013file_length\030\004 \001(\003\022\r\n\005b" +
      "egin\030\005 \001(\003\022\013\n\003end\030\006 \001(\003\"2\n\016UpdateInfoLis" +
      "t\022 \n\005infos\030\001 \003(\0132\021.proto.UpdateInfo\"I\n\016U" +
      "pdateResponse\022\021\n\tisSucceed\030\001 \001(\010\022$\n\013fail" +
      "ed_data\030\002 \003(\0132\017.proto.fileInfo2\213\001\n\017Meted" +
      "ataService\0226\n\007isExist\022\023.proto.QueryReque" +
      "st\032\024.proto.QueryResponse\"\000\022@\n\016updateMete" +
      "data\022\025.proto.UpdateInfoList\032\025.proto.Upda" +
      "teResponse\"\000BN\n,alluxio.client.file.cach" +
      "e.remote.net.serviceB\026MetedataServiceMan" +
      "agerP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_QueryResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_QueryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_QueryResponse_descriptor,
        new String[] { "IsExist", "Ip", "Port", });
    internal_static_proto_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_QueryRequest_descriptor,
        new String[] { "FileId", "Begin", "End", });
    internal_static_proto_UpdateInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_UpdateInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateInfo_descriptor,
        new String[] { "Host", "Port", "Info", });
    internal_static_proto_fileInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_fileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_fileInfo_descriptor,
        new String[] { "FileId", "FileLength", "Begin", "End", });
    internal_static_proto_UpdateInfoList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_UpdateInfoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateInfoList_descriptor,
        new String[] { "Infos", });
    internal_static_proto_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateResponse_descriptor,
        new String[] { "IsSucceed", "FailedData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
