// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metedataService.proto

package alluxio.client.file.cache.remote.grpc.service;

public interface QueryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.QueryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_exist = 1;</code>
   */
  boolean getIsExist();

  /**
   * <code>string ip = 2;</code>
   */
  String getIp();
  /**
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 3;</code>
   */
  int getPort();
}
