// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metedataService.proto

package alluxio.client.file.cache.remote.grpc.service;

public interface UpdateInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UpdateInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host = 1;</code>
   */
  String getHost();
  /**
   * <code>string host = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>.proto.fileInfo info = 3;</code>
   */
  boolean hasInfo();
  /**
   * <code>.proto.fileInfo info = 3;</code>
   */
  fileInfo getInfo();
  /**
   * <code>.proto.fileInfo info = 3;</code>
   */
  fileInfoOrBuilder getInfoOrBuilder();
}
