// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metedataService.proto

package alluxio.client.file.cache.remote.grpc.service;

public interface UpdateInfoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UpdateInfoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.UpdateInfo infos = 1;</code>
   */
  java.util.List<UpdateInfo>
      getInfosList();
  /**
   * <code>repeated .proto.UpdateInfo infos = 1;</code>
   */
  UpdateInfo getInfos(int index);
  /**
   * <code>repeated .proto.UpdateInfo infos = 1;</code>
   */
  int getInfosCount();
  /**
   * <code>repeated .proto.UpdateInfo infos = 1;</code>
   */
  java.util.List<? extends UpdateInfoOrBuilder>
      getInfosOrBuilderList();
  /**
   * <code>repeated .proto.UpdateInfo infos = 1;</code>
   */
  UpdateInfoOrBuilder getInfosOrBuilder(int index);
}
